"""nothing

Revision ID: d0a65493e5fe
Revises: b1aac619e92a
Create Date: 2020-04-18 17:07:59.122652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a65493e5fe'
down_revision = 'b1aac619e92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_category', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title', sa.VARCHAR(length=32), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_category', 'item', ['category'], unique=False)
    # ### end Alembic commands ###
